version: "3.8"

services:
  prtf-ui:
    image: node:18-alpine
    container_name: prtf-ui
    command: sleep infinity
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./:/app/
    working_dir: /app/
